"""
Django settings for exampleProject project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6^8ej-v+h9zhg_*jr9x$$1rxsu0gs)@tkun+o(3^kbzprji_##"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_yasg",
    "users.apps.UsersConfig",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "taggit",
    "modelcluster",
    "wagtail.contrib.modeladmin",
    "customers.apps.CustomersConfig",
    "customers.apps.CustomUsersAppConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]
AUTH_USER_MODEL = "users.User"

ROOT_URLCONF = "exampleProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "exampleProject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "django_project_db-1",
        "USER": "postgres",
        "PASSWORD": "0779641878",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

"""FIREBASE CREDENTIALS"""
FIREBASE_ACCOUNT_TYPE = "service_account"
FIREBASE_PROJECT_ID = "example-project-c5bb1"
FIREBASE_PRIVATE_KEY_ID = "10ba9a688d21ecc29d5149e6f887665cf9d71833"
FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDYIrolAAMCm9Rh\nZvpQ6hdffR43qdc3zDYHFgo7hCMIiMPkMYLToVrKN2vzsDOBbCk6V0opSmiOBrH2\nXRC4JrS62E4FZduyQ0IGmInDFmsqU0wGfMil3YgPasBO3g7O4d575qR8TtR3YRDB\nNpSUrRKmInbOIOyqMMBRwv+Xi0t6WQ+iWfjM3apJAAToyVMe+BnAD9VTjuE7J4rQ\nCT9/+bt0Zo7JNGZxJ+U9YVKxHp0SU0PUDqsAf4L4aRvHvo6+9sa4fxP3SQ2vddT9\njo3Km9fbc3uot9UojaR8/EGx3kQhoU244CdQ5fIPZPUcF449T5cnKXJYbrFwUXh2\n6zVmyYeLAgMBAAECggEAZG52mrzPqUWpwXztce3k4H0uLmVgWVAuBsrqBE/ZS5zp\nkb6j8Rz4KCDqq7jDpi8RVUe8cUVfIifgR/9kxn1N28ipMH7tQH9aTeBRm3JuZ6N/\nH0Cap+Ax2iAbrkonDWENVfuNkSm8NqDG/VEUZ6WolcRL+mp4Lnkq1JNM2ylh8D5Z\nQ2SXp9h7MBOY55/SU2HEMzGSoQVxnDCVG8grIcmwihxdgtdovWIU4/NCKzl/kxiP\nBn3SEZgKJId+iB3rgNtJ9UZK4EHJRwcBsFynVfpYG+HCr0gU2p2c6qdu4sHbXv7N\n8w+fsN6rY2M7DlqX035TTwGsGgjUzKpKeu7mnjn1aQKBgQD4c3Z7bZ1iUughQ53R\n2I7WH8DBRmaw+SyAWBD5FtKQFM6tlwoQPmbwzsAPxHMa3sdw8U8xPuWSKHV6L5Da\n0V91+iiWBjSAwePwC6XrgJTSxW4v8LQVQwmeb+Rph3zzGpqsCVWxfikhz6UmH4f3\nu1c4VjsGM46yvhmCp2bajamArQKBgQDes+d9oyxzO5UYIgQA9UWZbj4IGdVN9er9\nlkOfTwtTHts+SWJvpWshsSG1zWAwYHxUa2MGl/JcgqH4kf77uHkJgMJHCxeufOes\n8mS3A5fJI1q1Wm2eXbCMP6VyE6BN+ACQCI0nAlK4+slP/HirqnZovcX4Tm2pMMaw\n8Yr7npHYFwKBgQDjkfcbtVqsXh5LocCkHsUusmT/Y7naLlIpuQDK97Gk0bpB3JAW\nMuJdfjMD/kAkg5yRAic0h1UGXFLGuVzoYVEcIigcytA6g96B2FmA7gTjTn3QIZ0B\nwKbF3d2NH9I+Zsb3/5DjhBiu5KBz2/vR2WJZsvpbgswZQvDg8O7QD2QL/QKBgQC5\ne616fsUu1JlBGFOtWJs3RxJzPNDjtcaanuSDcxpDiJeiMQzDYEryLM2e1gcfQ71J\nsocvnq5FTqgIl9B/Zw2oVI17DkoTEgUDjn9DzsJEzCVoloBmPjIlHX12ndIOHliZ\nngWyT8UGPBoffHAkyj0Ez8prHSdIm09hYEwZdeCS0QKBgQCwDqNk0EW+FvuylCJf\nCZdRXB+XSXDVvpUrjZ6xBMRCfBiQdRHnZ+BusdAAq5mWgcGj+ljCIZa1S5A0oWwv\nOXFzos/TsPq0jkyvlJLgzu1HPcM/B23wiRP1w9AIGOFh3T2HgxvJKmxjqIKvCuRB\nSG+r4eZrXs9JqDGQB0v5XUaqVg==\n-----END PRIVATE KEY-----\n"
FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-o7qim@example-project-c5bb1.iam.gserviceaccount.com"
FIREBASE_CLIENT_ID = "103102050203157080338"
FIREBASE_AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
FIREBASE_TOKEN_URI = ("https://oauth2.googleapis.com/token",)
FIREBASE_AUTH_PROVIDER_X509_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
FIREBASE_CLIENT_X509_CERT_URL = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-o7qim%40example-project-c5bb1.iam.gserviceaccount.com"

# WAGTAIL SETTINGS

# This is the human-readable name of your Wagtail install
# which welcomes users upon login to the Wagtail admin.
WAGTAIL_SITE_NAME = "My Project"

# Replace the search backend
# WAGTAILSEARCH_BACKENDS = {
#  'default': {
#    'BACKEND': 'wagtail.search.backends.elasticsearch8',
#    'INDEX': 'myapp'
#  }
# }

# Wagtail email notifications from address
# WAGTAILADMIN_NOTIFICATION_FROM_EMAIL = 'wagtail@myhost.io'

# Wagtail email notification format
# WAGTAILADMIN_NOTIFICATION_USE_HTML = True

# Reverse the default case-sensitive handling of tags
TAGGIT_CASE_INSENSITIVE = True

WAGTAILADMIN_BASE_URL = "/admin/"
WAGTAILIMAGES_IMAGE_MODEL = "customers.CustomImage"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "django_cognito_jwt.JSONWebTokenAuthentication",
    ],
}

# AWS Configurations
AWS_STORAGE_BUCKET_NAME = "example-site-bucket-2023"
AWS_ACCESS_KEY_ID = "AKIA3JEGTLJ2K7DOFSMP"
AWS_SECRET_ACCESS_KEY = "aXjjCykcT9sx9ylSGXyoFfBii+a1Wkh08yD+Ghn7"
AWS_S3_REGION_NAME = "us-west-1"

DEFAULT_FILE_STORAGE = "storages.backends.s3.S3Storage"


COGNITO_AWS_REGION = "us-west-1"
COGNITO_USER_POOL = "us-west-1_w2sZHFw50"
COGNITO_AUDIENCE = "7f6oab5k8tm9bu29uifadsse8e"
