# Generated by Django 4.2.5 on 2023-09-10 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=31, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=31, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('currency_balance', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Currency Balance')),
                ('page_visits', models.IntegerField(verbose_name='Page Visits')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_date', models.DateField(verbose_name='Order Created Date')),
                ('item_count', models.IntegerField(verbose_name='Item Count')),
                ('description', models.CharField(max_length=1023, verbose_name='Description')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order', to='customers.customer', verbose_name='Customer')),
            ],
        ),
    ]
