# Generated by Django 4.2.5 on 2023-09-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('customers', '0002_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(help_text='Enter an Advertisement Title', max_length=255, verbose_name='Title')),
                ('description', models.CharField(help_text='Enter a Advertisement Description', max_length=255, verbose_name='Description')),
                ('how_to_donate', models.CharField(help_text='Enter a text for guidance', max_length=255, verbose_name='How to Donate')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
