# Generated by Django 4.2.5 on 2023-09-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('how_to_donate', models.CharField(max_length=255, verbose_name='How to Donate')),
            ],
        ),
    ]
