# Generated by Django 4.2.5 on 2023-09-22 04:22

from exampleProject import current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_alter_item_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(blank=True, default=current_user.get_current_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
