# Generated by Django 4.2.5 on 2023-09-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_item_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='item', to='customers.customimage', verbose_name='Images'),
        ),
        migrations.DeleteModel(
            name='FlexPage',
        ),
    ]
