# Generated by Django 4.2.5 on 2023-09-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_item_images_delete_flexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='customers.item'),
        ),
    ]
